services:
  db:
    image: postgres:16
    container_name: fplbr-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fpl}
      POSTGRES_USER: ${POSTGRES_USER:-fpl_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fpl_pass}
    ports:
      - "5432:5432"
    volumes:
      - fpl_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: fplbr-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS:-admin}
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    container_name: fpl_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  fpl_pgdata:
    name: fpl_pgdata
