name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Backend - Build & Test (JaCoCo)
        run: |
          cd backend
          ./mvnw -q -DskipITs=false clean verify
      - name: Frontend - Test & Coverage
        run: |
          cd fplbr-frontend
          npm ci
          npm test -- --coverage
