name: EOL Check

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "**" ]

jobs:
  eol-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Detect CRLF
        run: |
          if git grep -I $'\r' -- '*.java' '*.ts' '*.tsx' '*.js' '*.jsx' '*.json' '*.yml' '*.yaml' '*.xml' '*.md' '*.css' '*.html'; then
            echo "❌ CRLF detected in source files"
            exit 1
          fi
