name: PR Validate

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Backend - Build & Verify
        run: |
          cd backend
          chmod +x mvnw || true
          ./mvnw -B -DskipITs verify

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: fplbr-frontend/package-lock.json

      - name: Frontend - Lint & Tests
        run: |
          cd fplbr-frontend
          npm ci --no-fund --no-audit
          npm run lint --if-present
          npm test --if-present -- --watch=false

      - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            backend/target/surefire-reports
            fplbr-frontend/coverage


